### PR TITLE
use SubsystemWithProvider for newer version

### PR DESCRIPTION
**Pull request by Thaina**
When I try to upgrade project to 2022.2 it cause error that the subsystem api was changed. So I try to update related code on subsystem

### CODE REVIEW

**Comment by De-Panther** [comment]
Interesting. I didn't get to test newer Unity versions yet.
My guess is that relates to the Subsystem Manager package, and not the Unity Version, so it's better to use the asmdef to identify the Subsystem package version and have preprocessor directives for that. (e.g. #if SUBSYSTEM_V_4_1...)

**Comment by Thaina** [comment]
As far as I can see, the subsystem package was deprecated and in recent version of unity, but it was moved into core system of unity itself. So I think it would cause class naming conflict if we try to retain the package in unity 2022.2 and 2023

**Comment by De-Panther** [comment]
Maybe we can check version of another package, or if package exist?

**Comment by Thaina** [comment]
This is the new API

https://docs.unity3d.com/2022.2/Documentation/ScriptReference/SubsystemsImplementation.SubsystemWithProvider.html

And this is the deprecated API that was moved into core library

https://github.com/Unity-Technologies/UnityCsReference/blob/c0e1b832c0970e89c130a8be3f1b261a90acba36/Modules/Subsystems/Subsystem.deprecated.cs#L9

**Comment by De-Panther** [comment]
I understand, it's just that this issue is relevant also for some of the LTS versions (and some not), and I think that more elegant solution would be to use preprocessor directives based on packages versions, and not Unity Editor versions.

**Comment by De-Panther** [comment]
I understood from some 2021 LTS users that it happens there as well, but only on the most latest versions.
So instead of checking for 2021_3_OR_NEWER, as it's only some of the 2021.3 versions(I'm not sure, need to check that myself, on my current 2021.3 version it didn't happen), I want to check for `com.unity.xr.management` version.
Developers that told me about that issue, and I told them to downgrade the `com.unity.xr.management` package, it seems to solve their issue.
But a solution where the WebXR package check for version, is simpler to use and upgrade.

**Comment by De-Panther** [comment]
It seems that in version 4.3.1 of `com.unity.xr.management` they removed dependency on `com.unity.subsystemregistration` package for supported editors (2022.2+).
https://docs.unity3d.com/Packages/com.unity.xr.management@4.3/changelog/CHANGELOG.html

So in the `WebXR.asmdef` file, we can look for `com.unity.subsystemregistration` `Unity.Subsystem.Registration.asmdef` file, and if it doesn't exist, we should use your new code.

**Comment by hugodigio** [comment]
I use 2022.2.20 in my project, and I try to add WebXR on it ... but when I try to import it i Have this error:
`error CS0103: The name 'SubsystemRegistration' does not exist in the current context`
I supposed it's linked to this issue.

 I'm not an expert ... What I supposed to do so ? rollback my project to 2019 LTS ? or I can do something with 2022.2.20 ?
 
 thx you all !

**Comment by De-Panther** [comment]
> I use 2022.2.20 in my project, and I try to add WebXR on it ... but when I try to import it i Have this error: `error CS0103: The name 'SubsystemRegistration' does not exist in the current context` I supposed it's linked to this issue.
> 
> I'm not an expert ... What I supposed to do so ? rollback my project to 2019 LTS ? or I can do something with 2022.2.20 ?
> 
> thx you all !

for now you can downgrade the xr.management package to a version before 4.3.1

**Comment by hugodigio** [comment]
> for now you can downgrade the xr.management package to a version before 4.3.1

Thank you ! 
I will try this. I will make a report / complete procedure for those one have this problem in future.

EDIT: so to do this, I open Manifest.json in `/Packages` folder of my project (not in editor) and add this line:
`"com.unity.xr.management": "4.2.1"`
**Warning:** if you already have this line in your manifest (maybe with a different version), remove it.

I do this because there is no option in package manager to download old version of package (or I missed it)
After doing that, I return to editor and the package will be dowanloaded and installed.

I don't have the error since I do this. Thx you @De-Panther !

Do you think an package update of "webxr export" is possible in the future to fix this issue ?

 if I understood well, this "fix" will not work anymore on 2023.X release of unity ?
[https://docs.unity3d.com/Packages/com.unity.subsystemregistration@1.1/manual/index.html](https://docs.unity3d.com/Packages/com.unity.subsystemregistration@1.1/manual/index.html)

**Comment by De-Panther** [comment]
You are literally commenting on the PR that solves this :/

**Comment by De-Panther** [comment]
@Thaina I changed the branch this PR commits to, so I'll be able to do the needed changes.
Thanks for your help :)

**Pull request merged**
