### PR TITLE
Added bridge to XR Interaction Toolkit

### PR DESCRIPTION
**Pull request by someone-s**
Added WebXRHeadsetAdapter.cs, WebXRControllerAdapter.cs and a prefab for such use case

Configured asmdef and package json such that XRI Toolkit and InputSystem are not required, but the above scripts wont be available

The prefab should be added to a scene with the XRI Toolkit Setup Prefab (without any parent gameobject)

### CODE REVIEW

**Comment by De-Panther** [comment]
Awesome!
Looks like something that should be a separate package, or part of the WebXR Interactions package

**Comment by someone-s** [comment]
Should be trivial to do, will look into that

**Comment by De-Panther** [comment]
Ok, so you'll move it to WebXR Interactions?

**Comment by De-Panther** [comment]
I see you made it as a new repo.
Tell me once it's ready to release and I link to it where I can. (maybe I'll add a section in the readme)
Are you going to add it to OpenUPM?

**Comment by someone-s** [comment]
broken github action on my fork, figuring things out 😅

**Comment by someone-s** [comment]
disregard the earlier push

**Comment by De-Panther** [comment]
Are you on the WebXR discord?
https://discord.gg/webxr

**Comment by someone-s** [comment]
considering
a) it's still very incomplete in features
b) the current feature set is sufficient for use by the team I work in
c) the team I am working in will be pivoting to another project
I dont think I will be able to work on this for a few weeks

so I will write down important stuff here
and leave it on a repo:
https://github.com/someone-s/webxr-xri-toolkit-bridge
it should be simple to copy over to the main repo, just needs to change the author and links in package.json

both the controllers and headset are translated to xr toolkit based on the xr device simulator sample (suprisingly, the code that make the sample work are in the package and not the sample, so I've been able to reference those)
however the camera is structure differently, so seperate left and right camera are still created in runtime (none of the settings from the original camera is passed to the new ones, so this is a major missing feature)

**Comment by someone-s** [comment]
joined the webxr discrod just now

**Comment by De-Panther** [comment]
I much more prefer that it's in a separate repo.
I didn't try it, but it can be a great solution for those who wants to use XR Interaction Toolkit.
It's just that I don't want to maintain it, so it's a good thing that you made a new repo.
Of course, if there will be changes that are needed in the WebXR package, I'll be happy to merge them and maintain them.

If the current feature set is sufficient for use by your team, I think it'll be good for other devs as well, and if not, they can add features to it.


If it's ok with you, I can add it to OpenUPM, so it'll be easier for other devs to use.

**Comment by someone-s** [comment]
sure

**Comment by De-Panther** [comment]
Done - https://openupm.com/packages/com.someone-s.webxr-xrit-bridge/
Now dves can use your package by adding the scope `com.someone-s` to their OpenUPM scoped registries list, and select the package in the UPM window.

**Pull request closed without merging**
